export const cp3Dataset = [
    {
        sno: 1,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Vaasuthevan Vinothiny',
        nic: '818452217v',
        electricityAcNumber: 1816533300,
        bank: 'BOC',
        bankAccountNumber: 78745358,
        latitude: 9.163418,
        longitude: 80.675802,
        age: 43,
        gender: 'Male',
        phoneNumber: 772682750,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 2,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Sivaneethiraasha Sivamalar',
        nic: '816045096v',
        electricityAcNumber: 1816677108,
        bank: 'BOC',
        bankAccountNumber: 73129375,
        latitude: 9.160891,
        longitude: 80.67275,
        age: 43,
        gender: 'Male',
        phoneNumber: 773931137,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 3,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Kanesalingam  Thankaraani',
        nic: 196453100802,
        electricityAcNumber: 1818061406,
        bank: 'BOC',
        bankAccountNumber: 71974332,
        latitude: 9.160301,
        longitude: 80.675264,
        age: 60,
        gender: 'Male',
        phoneNumber: 764401162,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 7,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 4,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Thusijanan Vino',
        nic: '956834465v',
        electricityAcNumber: 1819703401,
        bank: 'BOC',
        bankAccountNumber: 71074395,
        latitude: 9.157781,
        longitude: 80.676085,
        age: 29,
        gender: 'Male',
        phoneNumber: 761531052,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 5,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Nirmalan Vinitha',
        nic: '797995746v',
        electricityAcNumber: 1816542105,
        bank: 'BOC',
        bankAccountNumber: 71100745,
        latitude: 9.15925,
        longitude: 80.677005,
        age: 45,
        gender: 'Female',
        phoneNumber: 741840785,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 6,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Sivarupan Nalinithamajanthi',
        nic: '755794716v',
        electricityAcNumber: 1816876604,
        bank: 'BOC',
        bankAccountNumber: 70261858,
        latitude: 9.159844,
        longitude: 80.67387,
        age: 49,
        gender: 'Male',
        phoneNumber: 778535783,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 7,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Murugaiya Selvaraththinam',
        nic: '781664277v',
        electricityAcNumber: 1816533505,
        bank: 'BOC',
        bankAccountNumber: 70446243,
        latitude: 9.161726,
        longitude: 80.673943,
        age: 46,
        gender: 'Male',
        phoneNumber: 776392528,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 8,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Sakirusain Navaruva',
        nic: '815412842v',
        electricityAcNumber: 1817854003,
        bank: 'BOC',
        bankAccountNumber: 70624273,
        latitude: 9.158479,
        longitude: 80.677123,
        age: 43,
        gender: 'Female',
        phoneNumber: 740234433,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 9,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Sivappirijankan Piriyanka',
        nic: '978310249v',
        electricityAcNumber: 1816677000,
        bank: 'BOC',
        bankAccountNumber: 76918514,
        latitude: 9.163053,
        longitude: 80.673995,
        age: 27,
        gender: 'Male',
        phoneNumber: 776009753,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 10,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Thampirasa Thangeshwaran',
        nic: '792445276v',
        electricityAcNumber: 1816551902,
        bank: 'BOC',
        bankAccountNumber: 73362991,
        latitude: 9.159006,
        longitude: 80.679017,
        age: 45,
        gender: 'Male',
        phoneNumber: 773698743,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 11,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Selvam Navakularajani',
        nic: '757113635v',
        electricityAcNumber: 1817028901,
        bank: 'BOC',
        bankAccountNumber: 70624228,
        latitude: 9.15829,
        longitude: 80.678869,
        age: 49,
        gender: 'Female',
        phoneNumber: 770257118,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 12,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Thavakaran Vinuja',
        nic: '948161532v',
        electricityAcNumber: 1818876809,
        bank: 'BOC',
        bankAccountNumber: 75760495,
        latitude: 9.157662,
        longitude: 80.678343,
        age: 30,
        gender: 'Female',
        phoneNumber: 767136381,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 13,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Nallu Thangarasa',
        nic: '522846813v',
        electricityAcNumber: 1818825309,
        bank: 'BOC',
        bankAccountNumber: 9985156,
        latitude: 9.156697,
        longitude: 80.678087,
        age: 72,
        gender: 'Male',
        phoneNumber: 766373274,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 14,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Kanthaiya Uthayakumar',
        nic: '800475180v',
        electricityAcNumber: 1816533408,
        bank: 'BOC',
        bankAccountNumber: 79452621,
        latitude: 9.157221,
        longitude: 80.682896,
        age: 44,
        gender: 'Male',
        phoneNumber: 771689819,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 15,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Puvanarasa Jeyalasa',
        nic: '835975444v',
        electricityAcNumber: 1816532606,
        bank: 'PEOPLES',
        bankAccountNumber: 20200120028372,
        latitude: 9.161923,
        longitude: 80.67266,
        age: 41,
        gender: 'Female',
        phoneNumber: 772518021,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 16,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Lokeshwaran Parameshwari',
        nic: '778094339v',
        electricityAcNumber: 1817853708,
        bank: 'BOC',
        bankAccountNumber: 9925091,
        latitude: 9.16248,
        longitude: 80.664578,
        age: 47,
        gender: 'Female',
        phoneNumber: 758239052,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 1,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 17,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Raasathurai Ravinthiran',
        nic: 197814302350,
        electricityAcNumber: 1817202804,
        bank: 'BOC',
        bankAccountNumber: 70490800,
        latitude: 9.162591,
        longitude: 80.677153,
        age: 46,
        gender: 'Male',
        phoneNumber: 772682750,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 18,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Ramesh Nishanthini',
        nic: '777553984v',
        electricityAcNumber: 1818115204,
        bank: 'BOC',
        bankAccountNumber: 70273016,
        latitude: 9.160337,
        longitude: 80.678653,
        age: 47,
        gender: 'Female',
        phoneNumber: 772467567,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 6,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 19,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Kanthaiya Sooriyakumar',
        nic: '781835331v',
        electricityAcNumber: 1816551600,
        bank: 'BOC',
        bankAccountNumber: 70463021,
        latitude: 9.158201,
        longitude: 80.679556,
        age: 36,
        gender: 'Female',
        phoneNumber: 762474578,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 20,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Chandrasekaran Kamalanathan',
        nic: '787205046v',
        electricityAcNumber: 1816534005,
        bank: 'BOC',
        bankAccountNumber: 78920464,
        latitude: 9.16247,
        longitude: 80.676521,
        age: 47,
        gender: 'Male',
        phoneNumber: 778878051,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 21,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Venthan Anura',
        nic: '816452007v',
        electricityAcNumber: 1816482005,
        bank: 'BOC',
        bankAccountNumber: 73140643,
        latitude: 9.1556,
        longitude: 80.682573,
        age: 43,
        gender: 'Female',
        phoneNumber: 778215392,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 22,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Uthayakumar Makeshwari',
        nic: '656952822v',
        electricityAcNumber: 1816482404,
        bank: 'BOC',
        bankAccountNumber: 70642922,
        latitude: 9.165956,
        longitude: 80.672806,
        age: 59,
        gender: 'Female',
        phoneNumber: 776392578,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 23,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Puliyankulam',
        beneficiaryName: 'Sinnaththampi subramaniyam',
        nic: '753014403v',
        electricityAcNumber: 1819739600,
        bank: 'BOC',
        bankAccountNumber: 76879947,
        latitude: 9.160471,
        longitude: 80.673264,
        age: 36,
        gender: 'Female',
        phoneNumber: 762474578,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 24,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Sivappirakasam Jeyasathiyanathan',
        nic: '761214489v',
        electricityAcNumber: 1819805204,
        bank: 'BOC',
        bankAccountNumber: 72289992,
        latitude: 9.14725,
        longitude: 80.652145,
        age: 38,
        gender: 'Male',
        phoneNumber: 777343396,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 25,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Vithusan kirupajini',
        nic: '988152480v',
        electricityAcNumber: 1821331907,
        bank: 'PEOPLES',
        bankAccountNumber: 20200170064956,
        latitude: 9.151774,
        longitude: 80.654076,
        age: 26,
        gender: 'Female',
        phoneNumber: 779467604,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 26,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Jeyapalan Kannikaparameshwari',
        nic: '586422286v',
        electricityAcNumber: 1814184007,
        bank: 'BOC',
        bankAccountNumber: 70610078,
        latitude: 9.149711,
        longitude: 80.651472,
        age: 64,
        gender: 'Female',
        phoneNumber: 774380587,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 27,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Nadarasa Kanesalingam ',
        nic: '701034406v',
        electricityAcNumber: 1817226002,
        bank: 'BOC',
        bankAccountNumber: 78818691,
        latitude: 9.135752,
        longitude: 80.649724,
        age: 46,
        gender: 'Male',
        phoneNumber: 766751175,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 28,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Sanmukanathan Selvarathan',
        nic: '842363535v',
        electricityAcNumber: 1817068601,
        bank: 'BOC',
        bankAccountNumber: 8838137,
        latitude: 9.133401,
        longitude: 80.653434,
        age: 40,
        gender: 'Male',
        phoneNumber: 776151050,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 29,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Sukanthan kajenthiny',
        nic: '847362480v',
        electricityAcNumber: 1816979406,
        bank: 'BOC',
        bankAccountNumber: 92808811,
        latitude: 9.118755,
        longitude: 80.639577,
        age: 40,
        gender: 'Female',
        phoneNumber: 762212522,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 30,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Thankarasa Thanusiya',
        nic: '976393651v',
        electricityAcNumber: 1817065602,
        bank: 'PEOPLES',
        bankAccountNumber: 20200140032820,
        latitude: 9.133401,
        longitude: 80.653434,
        age: 27,
        gender: 'Female',
        phoneNumber: 742264922,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 31,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Kanakasinkam Navaneethan',
        nic: 197536504372,
        electricityAcNumber: 1817069004,
        bank: 'BOC',
        bankAccountNumber: 75203028,
        latitude: 9.134749,
        longitude: 80.652627,
        age: 49,
        gender: 'Male',
        phoneNumber: 764852459,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 32,
        dsDivision: 'Oddusuddan',
        gnDivision: 'K/ Sammalankulam',
        beneficiaryName: 'Kirushnapillai Vimalanathan ',
        nic: 196709501570,
        electricityAcNumber: 1817226509,
        bank: 'BOC',
        bankAccountNumber: 78818920,
        latitude: 9.130256,
        longitude: 80.650347,
        age: 57,
        gender: 'Male',
        phoneNumber: 771887310,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 33,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Pichchai thankaththurai',
        nic: '612674736v',
        electricityAcNumber: 5715146607,
        bank: 'BOC',
        bankAccountNumber: 73164762,
        latitude: 9.167757,
        longitude: 80.644207,
        age: 63,
        gender: 'Male',
        phoneNumber: 775790633,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 34,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Kirusnamooththi senthamarai',
        nic: 197277000000,
        electricityAcNumber: 1816634409,
        bank: null,
        bankAccountNumber: null,
        latitude: 9.167857,
        longitude: 80.644352,
        age: 54,
        gender: 'Female ',
        phoneNumber: 770538732,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 35,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Ponnaija Moorththi',
        nic: '752763780v',
        electricityAcNumber: 1818196700,
        bank: 'BOC',
        bankAccountNumber: 91639580,
        latitude: 9.158822,
        longitude: 80.660946,
        age: 49,
        gender: 'Male',
        phoneNumber: 766466159,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 36,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Kiraisan Jeyaransini',
        nic: '745201920v',
        electricityAcNumber: 1819898601,
        bank: 'BOC',
        bankAccountNumber: 9730642,
        latitude: 9.165844,
        longitude: 80.661933,
        age: 50,
        gender: 'Female',
        phoneNumber: 774531032,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 37,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Rathakirusnan Arudsilan',
        nic: '790915623v',
        electricityAcNumber: 5715438209,
        bank: 'BOC',
        bankAccountNumber: 84288423,
        latitude: 9.164217,
        longitude: 80.661969,
        age: 45,
        gender: 'Male',
        phoneNumber: 771812392,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 38,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Jekatheeswaran Kavitha',
        nic: '793995713v',
        electricityAcNumber: 1820323005,
        bank: 'BOC',
        bankAccountNumber: 71414075,
        latitude: 9.164648,
        longitude: 80.658863,
        age: 45,
        gender: 'Female',
        phoneNumber: 770452051,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 39,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Mariyathase Ganarathi',
        nic: '925114383v',
        electricityAcNumber: 1816537101,
        bank: 'BOC',
        bankAccountNumber: 77441538,
        latitude: 9.169902,
        longitude: 80.649325,
        age: 32,
        gender: 'Female',
        phoneNumber: 771367938,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 40,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Maruthar kirushnan',
        nic: 197306803715,
        electricityAcNumber: 1818065800,
        bank: 'BOC',
        bankAccountNumber: 75091693,
        latitude: 9.165693,
        longitude: 80.644993,
        age: 52,
        gender: 'Male',
        phoneNumber: 778647359,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 7,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 41,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Ledsumanan Mokanakanthan',
        nic: '198718304962v',
        electricityAcNumber: 1822165202,
        bank: 'BOC',
        bankAccountNumber: 84711369,
        latitude: 9.164213,
        longitude: 80.647346,
        age: 36,
        gender: 'Male',
        phoneNumber: 777395053,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 42,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Poththinathan sivarasapopathi',
        nic: '766293948v',
        electricityAcNumber: 1819902102,
        bank: 'BOC',
        bankAccountNumber: 70658978,
        latitude: 9.167413,
        longitude: 80.647897,
        age: 48,
        gender: 'Female',
        phoneNumber: 742372463,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 43,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Kunasilan Shathanaa',
        nic: 198659904850,
        electricityAcNumber: 1817285408,
        bank: 'BOC',
        bankAccountNumber: 70377105,
        latitude: 9.170681,
        longitude: 80.657936,
        age: 38,
        gender: 'Female',
        phoneNumber: 772946319,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 44,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Kukathasan Thavamalar',
        nic: '548274273v',
        electricityAcNumber: 1816596906,
        bank: 'BOC',
        bankAccountNumber: 78897207,
        latitude: 9.171276,
        longitude: 80.649328,
        age: 70,
        gender: 'Female',
        phoneNumber: 778425338,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 45,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Sivapalan Komathi',
        nic: 199677804273,
        electricityAcNumber: 1820835006,
        bank: 'BOC',
        bankAccountNumber: 89046164,
        latitude: 9.169279,
        longitude: 80.642984,
        age: 28,
        gender: 'Female',
        phoneNumber: 770307890,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 46,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Sivasunthararasa Renuka',
        nic: '716624455V',
        electricityAcNumber: 1818991101,
        bank: 'BOC',
        bankAccountNumber: 9562207,
        latitude: 9.168583,
        longitude: 80.654885,
        age: 53,
        gender: 'Female',
        phoneNumber: 776590782,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 47,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Keppapilavu',
        beneficiaryName: 'Saravanamuththu Tharmarasa',
        nic: '733614110v',
        electricityAcNumber: 1820772705,
        bank: 'BOC',
        bankAccountNumber: 75659487,
        latitude: 9.277989,
        longitude: 80.750771,
        age: 50,
        gender: 'Male',
        phoneNumber: 774451162,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 48,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Kokkilai west',
        beneficiaryName: 'Mayilvaganam Sivasithamparam ',
        nic: 195824903340,
        electricityAcNumber: 1815948507,
        bank: 'BOC',
        bankAccountNumber: 78284560,
        latitude: 9.016931,
        longitude: 80.936901,
        age: 30,
        gender: 'Male',
        phoneNumber: 774052547,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 49,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Mullaitivu  south',
        beneficiaryName: 'Irarthanan supathra',
        nic: '846761055v',
        electricityAcNumber: 1823079105,
        bank: 'PEOPLES',
        bankAccountNumber: 20200170035704,
        latitude: 9.25305,
        longitude: 80.821224,
        age: 40,
        gender: 'Female',
        phoneNumber: 764479059,
        residency: 'Permanent',
        landAvailability: 'Equal or above 1/4 acres and less than 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'Yes',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 50,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Keppapilavu',
        beneficiaryName: 'Kumar vigitha',
        nic: '816824443v',
        electricityAcNumber: 1820596206,
        bank: 'BOC',
        bankAccountNumber: 76777317,
        latitude: 9.278134,
        longitude: 80.735985,
        age: 42,
        gender: 'Female',
        phoneNumber: 774539872,
        residency: 'Permanent',
        landAvailability: 'Equal or above 10 perched and less than 1/4 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 51,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Silawaththai',
        beneficiaryName: 'Navaraththinam Jeyanthi',
        nic: 196815603326,
        electricityAcNumber: 1814035109,
        bank: 'BOC',
        bankAccountNumber: 70952623,
        latitude: 9.245029,
        longitude: 80.825886,
        age: 60,
        gender: 'Male',
        phoneNumber: 766424084,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 52,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Silawaththai',
        beneficiaryName: 'Rasathurai Satheesh',
        nic: 199311503722,
        electricityAcNumber: 1820600106,
        bank: 'BOC',
        bankAccountNumber: 87447776,
        latitude: 9.242217,
        longitude: 80.829303,
        age: 31,
        gender: 'Male',
        phoneNumber: 770740087,
        residency: 'Permanent',
        landAvailability: 'Equal or above 1/4 acres and less than 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 53,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Silawaththai',
        beneficiaryName: 'S.Annakkodi',
        nic: '605864422v',
        electricityAcNumber: 1820123103,
        bank: 'BOC',
        bankAccountNumber: 89784750,
        latitude: 9.241166,
        longitude: 80.818699,
        age: 63,
        gender: 'Female',
        phoneNumber: 764543496,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 54,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Kokkilai west',
        beneficiaryName: 'Jeyarasa Amalotpavanayagi',
        nic: 196471210035,
        electricityAcNumber: 1818999005,
        bank: 'BOC',
        bankAccountNumber: 71022388,
        latitude: 9.012294,
        longitude: 80.932993,
        age: 60,
        gender: 'Female',
        phoneNumber: 762240971,
        residency: 'Permanent',
        landAvailability: 'Equal or above 10 perched and less than 1/4 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'Yes',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 55,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Keppapilavu',
        beneficiaryName: 'Ravichanthiran sivakumari',
        nic: 197674210040,
        electricityAcNumber: 1818350203,
        bank: 'BOC',
        bankAccountNumber: 83889348,
        latitude: 9.257112,
        longitude: 80.773881,
        age: 46,
        gender: 'Female',
        phoneNumber: 762755576,
        residency: 'Permanent',
        landAvailability: 'Equal or above 10 perched and less than 1/4 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'yes',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 56,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Valluvarpuram',
        beneficiaryName: 'Kumarasamy selvakumary',
        nic: '787105203v',
        electricityAcNumber: 1814377808,
        bank: 'BOC',
        bankAccountNumber: 71069432,
        latitude: 9.361352,
        longitude: 80.571993,
        age: 46,
        gender: 'Female',
        phoneNumber: 762385663,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 7,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 57,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Theravil',
        beneficiaryName: 'Manikkam Karunaithas',
        nic: '741364662v',
        electricityAcNumber: 1815607106,
        bank: 'BOC',
        bankAccountNumber: 85666315,
        latitude: 9.36544,
        longitude: 80.578563,
        age: 51,
        gender: 'Male',
        phoneNumber: 771243268,
        residency: 'Permanent',
        landAvailability: 'Equal or above 10 perched and less than 1/4 acres',
        familyMembers: 5,
        waterAvailability: 'No',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 58,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Udaiyarkaddu South',
        beneficiaryName: 'Lokeswaran Rejeena',
        nic: '877362248V',
        electricityAcNumber: 1817868608,
        bank: 'BOC',
        bankAccountNumber: 87362972,
        latitude: 9.347208,
        longitude: 80.583507,
        age: 37,
        gender: 'Female',
        phoneNumber: 778010109,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 59,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Vallipunam',
        beneficiaryName: 'Kalaikkumar logamatha',
        nic: '806494810v',
        electricityAcNumber: 1815705507,
        bank: 'PEOPLES',
        bankAccountNumber: 20200390001575,
        latitude: 9.339102,
        longitude: 80.637374,
        age: 44,
        gender: 'Female',
        phoneNumber: 779910035,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 60,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Manthuvil',
        beneficiaryName: 'Vengadasalam Veerasamy',
        nic: '581838190v',
        electricityAcNumber: 1816672408,
        bank: 'PEOPLES',
        bankAccountNumber: 20200150053534,
        latitude: 9.309766,
        longitude: 80.716714,
        age: 60,
        gender: 'Male',
        phoneNumber: 763496128,
        residency: 'Permanent',
        landAvailability: 'Equal or above 1/4 acres and less than 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 61,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Thevipuram',
        beneficiaryName: 'Arasarathnam Vasanthakumar',
        nic: 196606502329,
        electricityAcNumber: 1815739606,
        bank: 'BOC',
        bankAccountNumber: 20200300013224,
        latitude: 9.348806,
        longitude: 80.643372,
        age: 54,
        gender: 'Male',
        phoneNumber: 764685585,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'Yes',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 62,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Kombavil',
        beneficiaryName: 'Uthajavarman sriranjiny',
        nic: '916704429v',
        electricityAcNumber: 1818792001,
        bank: 'PEOPLES',
        bankAccountNumber: 20200180037585,
        latitude: 9.316793,
        longitude: 80.688692,
        age: 33,
        gender: 'Female',
        phoneNumber: 776973407,
        residency: 'Permanent',
        landAvailability: 'Equal or above 10 perched and less than 1/4 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 63,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Puthukkudiyiruppu west',
        beneficiaryName: 'Saththiyaraj viththiyavani',
        nic: '997743407V',
        electricityAcNumber: 1817237004,
        bank: 'BOC',
        bankAccountNumber: 80169515,
        latitude: 9.314651,
        longitude: 80.684371,
        age: 25,
        gender: 'Female',
        phoneNumber: 765657154,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 64,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Puthukkudiyiruppu west',
        beneficiaryName: 'Sinnappayal Arumukam',
        nic: 194210710051,
        electricityAcNumber: 1816474703,
        bank: 'BOC',
        bankAccountNumber: 74051815,
        latitude: 9.313793,
        longitude: 80.684956,
        age: 72,
        gender: 'Male',
        phoneNumber: 764629162,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 65,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Suthanthirapuram',
        beneficiaryName: 'Pirapakaran Sirithevy',
        nic: '905664786V',
        electricityAcNumber: 1816080004,
        bank: 'BOC',
        bankAccountNumber: 88547133,
        latitude: 9.369369,
        longitude: 80.625143,
        age: 34,
        gender: 'Female',
        phoneNumber: 767839532,
        residency: 'Other',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 66,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Visuvamadu West',
        beneficiaryName: 'Karuneshwaran jeyamathy',
        nic: 198053803119,
        electricityAcNumber: 1818622602,
        bank: 'BOC',
        bankAccountNumber: 89549938,
        latitude: 9.385032,
        longitude: 80.53371,
        age: 44,
        gender: 'Female',
        phoneNumber: 778426993,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 67,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Mannakandal',
        beneficiaryName: 'Sivapalan Pushparani',
        nic: '826142448v',
        electricityAcNumber: 1818150603,
        bank: 'BOC',
        bankAccountNumber: 82486269,
        latitude: 9.204053,
        longitude: 80.674479,
        age: 42,
        gender: 'Female',
        phoneNumber: 770345431,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 68,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Mannakandal',
        beneficiaryName: 'Balasuppiramaniyam Rajeswary',
        nic: '685144840v',
        electricityAcNumber: 1818106507,
        bank: 'BOC',
        bankAccountNumber: 71115584,
        latitude: 9.207305,
        longitude: 80.681065,
        age: 57,
        gender: 'Female',
        phoneNumber: 775374103,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'Medium',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 69,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Manikkapuram',
        beneficiaryName: 'Aarumugam Kanthasami',
        nic: '531625277v',
        electricityAcNumber: 1815406704,
        bank: 'BOC',
        bankAccountNumber: 92532012,
        latitude: 9.359098,
        longitude: 80.563799,
        age: 68,
        gender: 'Female',
        phoneNumber: 775960435,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'No',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 70,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Udaiyarkaddu North',
        beneficiaryName: 'Thaiyakarasa Nakeswari',
        nic: 196065804539,
        electricityAcNumber: 1822164303,
        bank: 'BOC',
        bankAccountNumber: 90549416,
        latitude: 9.364903,
        longitude: 80.598366,
        age: 64,
        gender: 'Female',
        phoneNumber: 765661605,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 1,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'Yes',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 71,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Visuvamadu West',
        beneficiaryName: 'Velu Rajakobal',
        nic: '723384708v',
        electricityAcNumber: 1817913808,
        bank: 'BOC',
        bankAccountNumber: 70997062,
        latitude: 9.3595,
        longitude: 80.537702,
        age: 52,
        gender: 'Male',
        phoneNumber: 778588801,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Asbestos Sheets',
    },
    {
        sno: 72,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Visuvamadu West',
        beneficiaryName: 'Arumugam Sivagnanam',
        nic: '671343468v',
        electricityAcNumber: 1815936800,
        bank: 'BOC',
        bankAccountNumber: 70989398,
        latitude: 9.406593,
        longitude: 80.528519,
        age: 57,
        gender: 'Male',
        phoneNumber: 779672313,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 73,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Visuvamadu West',
        beneficiaryName: 'Selvarasa Rasenthiran',
        nic: '783095599v',
        electricityAcNumber: 1818454009,
        bank: 'BOC',
        bankAccountNumber: 73018331,
        latitude: 9.362918,
        longitude: 80.54366,
        age: 46,
        gender: 'Male',
        phoneNumber: 774103192,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 74,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Kokkilai West',
        beneficiaryName: 'Navaradnam Selvarani',
        nic: '566044218v',
        electricityAcNumber: 1821155203,
        bank: 'PEOPLES',
        bankAccountNumber: 20200250031155,
        latitude: 80.942695,
        longitude: 9.007222,
        age: 69,
        gender: 'Female',
        phoneNumber: 770235520,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 75,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Kokkilai West',
        beneficiaryName: 'Sujithkumara Ponseha Natheeka',
        nic: '795323004v',
        electricityAcNumber: 1816509205,
        bank: 'BOC',
        bankAccountNumber: 71775368,
        latitude: 80.921208,
        longitude: 9.047442,
        age: 45,
        gender: 'Female',
        phoneNumber: 779573639,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 76,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Kokkilai West',
        beneficiaryName: 'Vijayanathan Narmatha',
        nic: '913190050v',
        electricityAcNumber: null,
        bank: null,
        bankAccountNumber: 77542851,
        latitude: 80.915202,
        longitude: 9.047552,
        age: 34,
        gender: 'Female',
        phoneNumber: 769838051,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 77,
        dsDivision: 'Maritimepattu',
        gnDivision: 'Kokkuthoduvaai North',
        beneficiaryName: 'S. Komaleswary',
        nic: '605035132v',
        electricityAcNumber: 1824005806,
        bank: 'BOC',
        bankAccountNumber: 71843454,
        latitude: 80.913571,
        longitude: 9.059613,
        age: 64,
        gender: 'Female',
        phoneNumber: 775793602,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 78,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Valluvapuram',
        beneficiaryName: 'Santhirapalan Malathi',
        nic: 197451301247,
        electricityAcNumber: 1815420006,
        bank: 'BOC',
        bankAccountNumber: 71052369,
        latitude: 80.573257,
        longitude: 9.3607,
        age: 49,
        gender: 'Female',
        phoneNumber: 766741562,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 1,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 79,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Theravil',
        beneficiaryName: 'SuntharrarajnValliyamma',
        nic: 195457601912,
        electricityAcNumber: 1819125300,
        bank: 'BOC',
        bankAccountNumber: 85393740,
        latitude: 80.578563,
        longitude: 9.36544,
        age: 70,
        gender: 'Female',
        phoneNumber: 771243268,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 80,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Visuvamadu West',
        beneficiaryName: 'Mathivarnan rajitha',
        nic: 197650702441,
        electricityAcNumber: 1815612509,
        bank: 'BOC',
        bankAccountNumber: 9991793,
        latitude: 80.5372,
        longitude: 9.381872,
        age: 48,
        gender: 'Female',
        phoneNumber: 761180788,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 81,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Suthanthirapuram',
        beneficiaryName: 'Vijayakumari Makeswari',
        nic: '686213951 v',
        electricityAcNumber: 1816764701,
        bank: 'BOC',
        bankAccountNumber: 71908569,
        latitude: 80.602703,
        longitude: 9.351351,
        age: 56,
        gender: 'Female',
        phoneNumber: 743011943,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 82,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Vallipunam',
        beneficiaryName: 'Kalakaran  Saranja',
        nic: '907795012V',
        electricityAcNumber: null,
        bank: null,
        bankAccountNumber: null,
        latitude: 80.645437,
        longitude: 9.334133,
        age: 33,
        gender: 'female',
        phoneNumber: 760646919,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 83,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Viththiyapuram',
        beneficiaryName: 'Ravichsanthiran Pushparani',
        nic: '706281772v',
        electricityAcNumber: 5712190400,
        bank: 'BOC',
        bankAccountNumber: 9348227,
        latitude: 80.650306,
        longitude: 9.165921,
        age: 54,
        gender: 'Female',
        phoneNumber: 770691556,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 84,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Olumadu',
        beneficiaryName: 'Rarajagobal Selvarani',
        nic: '707895080v',
        electricityAcNumber: 1819367401,
        bank: 'BOC',
        bankAccountNumber: 70594524,
        latitude: 80.478106,
        longitude: 9.156215,
        age: 54,
        gender: 'Female',
        phoneNumber: 775571007,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 85,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Olumadu',
        beneficiaryName: 'Rakurajan Rasakumari',
        nic: '715134894v',
        electricityAcNumber: 1818687909,
        bank: 'PEOPLES',
        bankAccountNumber: 165200257861228,
        latitude: 80.477869,
        longitude: 9.154871,
        age: 53,
        gender: 'Female',
        phoneNumber: 778988442,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 86,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Olumadu',
        beneficiaryName: 'Sivarasa Puvaneshwari',
        nic: '757895080v',
        electricityAcNumber: 1819398501,
        bank: 'BOC',
        bankAccountNumber: 70021444,
        latitude: 80.478447,
        longitude: 9.154415,
        age: 49,
        gender: 'Female',
        phoneNumber: 775860683,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 87,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Olumadu',
        beneficiaryName: 'Srikumar mehala',
        nic: '918361510v',
        electricityAcNumber: 1822159504,
        bank: 'BOC',
        bankAccountNumber: 87420849,
        latitude: 80.478565,
        longitude: 9.154198,
        age: 33,
        gender: 'Female',
        phoneNumber: 770647473,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 3,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 88,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Venukaanthan Logeni',
        nic: 200180705070,
        electricityAcNumber: 1821159403,
        bank: 'BOC',
        bankAccountNumber: 81164592,
        latitude: 80.632935,
        longitude: 9.174602,
        age: 23,
        gender: 'Female',
        phoneNumber: 767532705,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 89,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Anantharupan Rathini',
        nic: '816363136v',
        electricityAcNumber: 1817382101,
        bank: 'BOC',
        bankAccountNumber: 71633366,
        latitude: 80.637843,
        longitude: 9.189672,
        age: 43,
        gender: 'Female',
        phoneNumber: 779009427,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 6,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 90,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Pathmanathan Menaka',
        nic: '816904773v',
        electricityAcNumber: 1816127302,
        bank: 'BOC',
        bankAccountNumber: 83613412,
        latitude: 80.63682,
        longitude: 9.17591,
        age: 43,
        gender: 'Female',
        phoneNumber: 743736489,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 91,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Alakurasha Kavitha',
        nic: '818093845v',
        electricityAcNumber: 1816127000,
        bank: 'PEOPLES',
        bankAccountNumber: 20200200000670,
        latitude: 80.634026,
        longitude: 9.179761,
        age: 43,
        gender: 'Female',
        phoneNumber: 760480509,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 92,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Thevarasa Thavachchelvi',
        nic: '750015921v',
        electricityAcNumber: 1817382306,
        bank: 'BOC',
        bankAccountNumber: 70084701,
        latitude: 80.639255,
        longitude: 9.194503,
        age: 49,
        gender: 'Female',
        phoneNumber: 768320711,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 93,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Ramakirushnan Thilakam',
        nic: '838221920v',
        electricityAcNumber: null,
        bank: null,
        bankAccountNumber: null,
        latitude: 80.632825,
        longitude: 9.175145,
        age: 41,
        gender: 'Female',
        phoneNumber: 767594144,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 94,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Vaakisan Jamuna',
        nic: '733184051v',
        electricityAcNumber: 1816128708,
        bank: 'BOC',
        bankAccountNumber: 70399385,
        latitude: 80.634387,
        longitude: 9.172948,
        age: 51,
        gender: 'Female',
        phoneNumber: 775190141,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 5,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 95,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Pathmanathan Kirishnakumari',
        nic: null,
        electricityAcNumber: 1816914002,
        bank: null,
        bankAccountNumber: null,
        latitude: 80.633473,
        longitude: 9.183685,
        age: 56,
        gender: 'Female',
        phoneNumber: 773476946,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 96,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Karuvelankandal',
        beneficiaryName: 'Arunthavarasa anusiya',
        nic: 199083400388,
        electricityAcNumber: 1818371006,
        bank: 'BOC',
        bankAccountNumber: 71195544,
        latitude: 80.686837,
        longitude: 9.175905,
        age: 36,
        gender: 'Female',
        phoneNumber: 762171372,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 97,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Karuvelankandal',
        beneficiaryName: 'Suganthan Thiyagarubika',
        nic: '906193183v',
        electricityAcNumber: 1819698602,
        bank: 'BOC',
        bankAccountNumber: 73034370,
        latitude: 80.68003,
        longitude: 9.168867,
        age: 36,
        gender: 'Female',
        phoneNumber: 772620300,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 2,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 98,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Katchilaimadu',
        beneficiaryName: 'Kantharoopan kamaleswary',
        nic: 196765103604,
        electricityAcNumber: 1818319004,
        bank: 'BOC',
        bankAccountNumber: 73253658,
        latitude: 80.660548,
        longitude: 9.178557,
        age: 35,
        gender: 'Female',
        phoneNumber: 778106582,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 99,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Thaddayamalai',
        beneficiaryName: 'Pathmanathan Sivarani',
        nic: 196851904040,
        electricityAcNumber: 1816817600,
        bank: 'BOC',
        bankAccountNumber: 71883634,
        latitude: 80.633473,
        longitude: 9.183685,
        age: 35,
        gender: 'Female',
        phoneNumber: 779476246,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 100,
        dsDivision: 'Oddusuddan',
        gnDivision: 'Kanagaratnapuram',
        beneficiaryName: 'Ramusivan Ranjini',
        nic: '865244347v',
        electricityAcNumber: 1818811200,
        bank: 'BOC',
        bankAccountNumber: 73078516,
        latitude: 80.636525,
        longitude: 9.175821,
        age: 40,
        gender: 'Female',
        phoneNumber: 771184491,
        residency: 'Permanent',
        landAvailability: 'above 1/2 acres',
        familyMembers: 4,
        waterAvailability: 'High',
        microIrrigation: 'No',
        motorAvailability: 'Yes',
        jsb: 'no',
        roofType: 'Clay Roof Tiles',
    },
    {
        sno: 101,
        dsDivision: 'Maritiempattu',
        gnDivision: 'Alampil',
        beneficiaryName: 'Hospital',
        nic: null,
        electricityAcNumber: null,
        bank: null,
        bankAccountNumber: null,
        latitude: 80.854151,
        longitude: 9.163669,
        age: null,
        gender: null,
        phoneNumber: null,
        residency: null,
        landAvailability: null,
        familyMembers: null,
        waterAvailability: null,
        microIrrigation: null,
        motorAvailability: null,
        jsb: null,
        roofType: null,
    },
    {
        sno: 102,
        dsDivision: 'Puthukudiyiruppu',
        gnDivision: 'Puthukudiyiruppu',
        beneficiaryName: 'School',
        nic: null,
        electricityAcNumber: null,
        bank: null,
        bankAccountNumber: null,
        latitude: 80.693992,
        longitude: 9.312765,
        age: null,
        gender: null,
        phoneNumber: null,
        residency: null,
        landAvailability: null,
        familyMembers: null,
        waterAvailability: null,
        microIrrigation: null,
        motorAvailability: null,
        jsb: null,
        roofType: null,
    },
] as const;
